# -*- coding: utf-8 -*-
"""BharatIntern2(DS).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dO5a3jltxyb_20OOHCF98X__Kn2CA2Fz
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
data



data = data.drop(['Name', 'Ticket', 'Cabin', 'PassengerId'], axis=1)
data['Age'].fillna(data['Age'].mean(), inplace=True)
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)
data

label_encoder = LabelEncoder()
data['Sex'] = label_encoder.fit_transform(data['Sex'])
data['Embarked'] = label_encoder.fit_transform(data['Embarked'])
label_encoder

X = data.drop('Survived', axis=1)
y = data['Survived']
X
y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
scaler
X_train
X_test

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
model

y_pred = model.predict(X_test)
y_pred

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')
print(classification_report(y_test, y_pred))

new_data = pd.DataFrame({'Pclass': [3], 'Sex': [1], 'Age': [30], 'SibSp': [0], 'Parch': [0], 'Fare': [7.25], 'Embarked': [0]})
new_data = scaler.transform(new_data)
prediction = model.predict(new_data)
print(f'Predicted survival: {prediction[0]}')